# netlify.toml (located at the root of your Git repository)
[build]
  base = "fitness-frontend/"   # This now points to your frontend folder
  publish = "fitness-frontend/dist/" # This is the build output folder inside fitness-frontend
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200